### ISSUE TITLE
Cognatesets column

### ISSUE THREAD

**Issue by Anaphory** [clld/lexibank#11]
I have written a cognatesets column for the data tables, which I intend to use for the single-concept views. You may find it relevant, or have a better idea how to implement it.

https://github.com/Anaphory/lexibank/tree/cognatesets_column

The specific commit is https://github.com/Anaphory/lexibank/commit/7bca27fa509471f07970d90675546fcfe9b9ef5b

**Comment by xrotwang** [comment]
Columns like this - i.e. ones that pull in all related objects per row - are very performance-critical; the way it is implemented now will (presumably) result in at least one additional DB query per row. One can get around this by instruction SQLAlchemy to pull in the requested data via JOINs, doing something like

``` python
    query = query.options(joinedload_all(Counterpart.cognateset, ...))
```

in the table's `base_query` method. But for this particular table, the query is already quite expensive; so adding more JOINs here may result in unacceptably slow queries.

**Comment by xrotwang** [comment]
If the information is absolutely necessary in the table, one way around this is de-normalization; i.e. pre-computing the related `Cognateset` objects per `Counterpart` in `prime_cache` when initializing the DB, and storing - say - their `id` as a list in `Counterpart.jsondata`. Then you could use this data in `CognatesetsCol.format` to construct the links.

**Comment by Anaphory** [comment]
Ah, okay. Thank you! I'll have to look into that at some point (raised an issue in my fork) – I think it is necessary for my DB, but I don't want to hack it for performance yet.
