### ISSUE TITLE
Should data source paths be specified in the `.ini` file?

### ISSUE THREAD

**Issue by Anaphory** [clld/lexibank#2]
I have noticed it in grambank as well:
The directories containing the data source `.csv` etc. files are specified in the source code.
Following the concept of splitting data and code, it seems reasonable to specify the data in the `.ini` files, for example `development.ini`, which connect data (eg. the sql databases to be served from) also in other instances.
Is there a good clean way to specify the data source path in the (to take the case I currently use) `development.ini` file and use that in `initializedb.py` etc.?
Does anything speak against doing so?

**Comment by xrotwang** [comment]
No, that's perfectly reasonable. So far, `initializedb.py` is really project/app-specific code, and by extension even machine-specific code tailored to the environment of the data curator for the given project. This may change once CLDF is mature enough to add a good default import routine.

Specifying and using config settings defined in `development.ini` can be done the regular pyramid way, i.e. defining settings in the `app:main` section, preferably with a custom prefix (e.g. `myapp.setting = ...`), and accessing these settings in `initilaizedb.py` as `args.env['registry'].settings['myapp.setting']`.
