### ISSUE TITLE
Cognate class template seems to be missing.

### ISSUE THREAD

**Issue by Anaphory** [clld/lexibank#5]
I have finally included cognate sets in my local version of lexibank, but when I follow a “cognate set” link, I get a text file looking like this:

```
{"pk_i": 2, "created": "2016-08-23T15:35:13Z", "active": true, "rscname": "Cognateset", "url": "http://localhost:6544/cognatesets/2f2784a2-6947-11e6-89e2-7845c41c79e3", "dataset": "lexibank129554", "updated": "2016-08-23T15:35:13Z", "id": "2f2784a2-6947-11e6-89e2-7845c41c79e3", "name": "m"}
```

I guess the cognate class template (`cognatesets`) is missing, do you have an unmerged one or shall I contribute one for your use?

**Comment by xrotwang** [comment]
AFAIKT it's there: https://github.com/clld/lexibank/tree/master/lexibank/templates/cognateset

**Comment by Anaphory** [comment]
That should teach me to not neglect pulling from `official` (i.e. here) for far too long.
