### ISSUE TITLE
Column filters don't partially match

### ISSUE THREAD

**Issue by Anaphory** [clld/lexibank#8]
This may be an issue of the underlying clld pyramid framework, but I just noticed it in my lexibank installation and want to report it before I forget:

Column filtering (typing text in the input on top of a table) only matches full values, not partial values. (eg. typing "2" should show "2pl", but doesn't; "2pl" reappears when typing the full "2pl")

**Comment by xrotwang** [comment]
This behaviour can be customized per `Column` via `Column.search`. The default for `Unicode` columns should be matching the query anywhere in the value, though, see [here](https://github.com/clld/clld/blob/master/clld/web/datatables/base.py#L164). So I'd need to know which column you are referring to, to decide whether that's a bug or not.

**Comment by Anaphory** [comment]
I noticed it for the `IdCol` named `id` and the `LinkCol` named `Concept` in `/parameters` (generated by a `Concepts` table registered as `parameters`)

**Comment by xrotwang** [comment]
Ok. Both times this is intended behaviour, I think. So maybe time for you to bootstrap a proper app, where you can overwrite things without having to rely on upstream :)

**Comment by Anaphory** [comment]
I get it for the ID column, but filtering by concept name looks reasonable to me, in particular because there is no separate gloss (etc.) column I could filter by.
(Also, that's what I'm doing, but I like being somewhat compatible, merging from and feeding back to upstream.)

**Comment by xrotwang** [comment]
In the second case that's actually a bug in `lexibank.datatables`. The column must be defined with a name of `name` to make sure the correct column is used for filtering. So in the definition of the `Concepts` table it should read

``` python
            LinkCol(self, 'name', sTitle='Concept'),
```

**Comment by Anaphory** [comment]
Is the reasoning as follows?

A `Unicode` column should support partial matching.

```
LinkCol(self, 'name', sTitle='Concept')
```

is a Unicode column, because it takes all the object's `name`s, and `Concept.name` is a `Column(Unicode)`.

```
LinkCol(self, 'Concept')
```

is trying to display the `Concept` column of the concepts table, failing, and defaulting to displaying all objects in the concepts table, which falls back to displaying their names. It is therefore not a `Unicode` column, but something like a `Concept` column, which does not automatically do partial matching.

**Comment by xrotwang** [comment]
Mostly correct. Since `Concept` doesn't match any attribute of a `clld.db.models.common.Parameter` object, filtering and ordering for this `LinkCol` are undefined (and in fact do not work - the filter doesn't even match exact values). So basically the old `Column` definition was a bug. `Parameter.name` was displayed as link label for the column because this is what an objects [default representation as string](https://github.com/clld/clld/blob/master/clld/db/meta.py#L365-L372) looks like.
